### ISSUE TITLE
Epic 4: Create identity

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/theoutlet#24]
### Create identity

1st screen: 
Action button to generate new key-pair, click leads to 2nd screen

2nd screen:
Create identity page, with:

-  the public address
-  an empty field to fill in a username
-  a button to add an image 
-  confirm and create button disabled 

After filling in a username and uploading an image, the confirm and create button is enabled.
A new button appears to change the image once an image has been uploaded.

- [x] Build the UI
- [ ] Style the UI
- [ ] Generate the keypair and identity

[sketch file](https://www.sketch.com/s/ad2db32e-e7c1-4cd8-8971-688c438eb58c)
![Image](https://user-images.githubusercontent.com/9036081/204814084-aeab31eb-ddf1-460f-aa1a-30ccc3c9e958.png)

![Image](https://user-images.githubusercontent.com/9036081/204814086-346bec8f-1687-4383-868b-10e31d852dd6.png)
![Image](https://user-images.githubusercontent.com/9036081/204814085-d648d018-e160-4f30-90a9-0b3ff65c87be.png)

**Comment by david-gauquelin** [comment]
I would make this Epic 4. See my comment on #25. @kikipluche @vojtechsimetka

**Comment by kikipluche** [comment]
@david-gauquelin 2 questions: 

1. when does the confirm and create button change from disabled to enabled: only after name+avatar are filled in? Or only name? Or can i create an identity with only my pub address to show? 
2. What about resizing and/or rotating the image, how do we visualise this possibility?

**Comment by david-gauquelin** [comment]
> @david-gauquelin 2 questions:
> 
> 1. when does the confirm and create button change from disabled to enabled: only after name+avatar are filled in? Or only name? Or can i create an identity with only my pub address to show?
This is all for us to decide, what's mandatory or not.
> 2. What about resizing and/or rotating the image, how do we visualise this possibility?
I suppose that for now we would not offer the option to crop manually, just do something automatic (make it fit based on the width/height) based on the image you upload

**Comment by kikipluche** [comment]
this epic is no longer valid
