### ISSUE TITLE
Epic 3: Choose identity

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/theoutlet#25]
### Choose identity

The user can choose from a list of identities, 
default there is 1 anonymous group identity.
When user has created more identities, those will be listed here.

Action button to create new identity, leads to page create identity.

TODO:
- [x] Build the UI
    - [x] Change the identity on click  #39
- [ ] Style the UI

[sketch file](https://www.sketch.com/s/ad2db32e-e7c1-4cd8-8971-688c438eb58c)

![Image](https://user-images.githubusercontent.com/9036081/204811848-bc148558-feab-424c-85bc-1ecf7c50fcce.png)
![Image](https://user-images.githubusercontent.com/9036081/204811893-75688a53-da51-46cf-a8e2-92ccaebecd76.png)
![Image](https://user-images.githubusercontent.com/9036081/204811960-c1ea6579-6521-4381-9d7e-574603ba51de.png)
